blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.article, name='article_page'),
    url(r'^article/edit/(?P<article_id>\d+)$', views.edit, name='edit_page'),
    url(r'^article/action$', views.action, name='edit_action'),
]

blog2/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^blog2/', include('blog2.urls')),
]

blog/models.py
from __future__ import unicode_literals
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    create_time = models.TimeField(null=True)
    
    def __str__(self):
        return self.title

blog2/models.py
from django.db import models
# Create your models here.

blog/views.py
from django.shortcuts import render, redirect
from . import models
# from django.http import HttpResponse


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

def article(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})

def edit(request,article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article':article})


def action(request):
    article_id = request.POST.get('article_id','0')
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    if str(article_id) == '0':
        models.Article.objects.create(title=title, content=content)
        return redirect('/blog/index')  
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog2/views.py
from django.shortcuts import render
# from django.http import HttpResponse


def index(request):
    return render(request, 'blog2/index.html')

# Create your views here.

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{article.title}}</h1>
    <h3>{{article.content}}</h3>
    <br><br><br>
    <h2><a href="{% url 'blog:edit_page' article.id %}">修改文章</a></h2>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
        <label for="">文章标题<input type="text" name="title" value="{{article.title}}"></label><br>
        <label for="">文章内容<textarea name="content" cols="30" rows="10">{{article.content}}</textarea></label><br>
        <input type="submit" value="提交">
    </form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>{{article.title}}</div>
    <div>{{article.content}}</div>
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>hello blog2</div>
</body>
</html>